[tool.coverage.run]
omit = [
    "src/python/tests/*",
]

[tool.mypy]
files = "./src/python"
exclude = "/tests/"

disallow_untyped_defs = true
explicit_package_bases = true
ignore_missing_imports = true
strict_equality = true
warn_redundant_casts = true
warn_unreachable = true

[tool.pytest.ini_options]
pythonpath = "src/python"

[tool.ruff]
line-length = 120
target-version = "py313"
src = ["src/python"]

[tool.ruff.lint]
ignore = ["E203"]
